# Generated by Django 4.2.6 on 2023-10-25 03:24

from django.db import migrations


class Migration(migrations.Migration):

    # dependencies = [
    #     ('panel', '0001_initial'),
    # ]

    operations = [
        migrations.RemoveField(
            model_name='estado',
            name='pais',
        ),
        migrations.DeleteModel(
            name='Pais',
        ),
    ]
