# Generated by Django 4.2.6 on 2023-10-25 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    # dependencies = [
    #     ('panel', '0003_alter_estado_nombre_alter_municipio_nombre'),
    # ]

    operations = [
        migrations.AddField(
            model_name='municipio',
            name='codigo',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
