# Generated by Django 4.2.6 on 2023-10-25 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    # dependencies = [
    #     ('panel', '0004_municipio_codigo'),
    # ]

    operations = [
        migrations.RemoveField(
            model_name='estado',
            name='pais',
        ),
        migrations.AlterField(
            model_name='municipio',
            name='codigo',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.DeleteModel(
            name='Pais',
        ),
    ]
