# Generated by Django 4.2.6 on 2023-10-29 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0006_remove_estado_pais_delete_pais'),
    ]

    operations = [
        # migrations.DeleteModel(
        #     name='Pais',
        # ),
        migrations.AlterField(
            model_name='municipio',
            name='codigo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
