# Generated by Django 4.2.6 on 2023-10-29 05:26

from django.db import migrations


class Migration(migrations.Migration):

    # dependencies = [
    #     ('panel', '0007_delete_pais_alter_municipio_codigo'),
    # ]

    operations = [
        migrations.DeleteModel(
            name='Pais',
        ),
    ]
